; Project Euler Problem 2
; Solution by nathan dotz - nathan (period) dotz (at sign) gmail (period) com
;
; Each new term in the Fibonacci sequence is generated by adding
; the previous two terms. By starting with 1 and 2, the first
; 10 terms will be:
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; Find the sum of all the even-valued terms in the sequence
; which do not exceed four million.
;

#lang racket

(provide fib evens answer)

(require "util.rkt")

(define (fib n)
  (define (fib-worker n stack)
	  (if (<= n (car stack))
		stack
                (let* ([fst (first stack)]
                       [snd (second stack)]
                       [new-top (+ fst snd)])
                  (fib-worker n (cons new-top stack)))))
  (if (< n 1)
      '()
      (fib-worker n '(1 1)))
  )

(define (evens lst)
  (filter even? lst))

(define (answer)
  (sum (evens (fib 4000000))))
